services:
  db:
    image: postgres:15
    container_name: fastapi_cms_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_cms_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db  # override only host for Docker networking
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # live code reload

volumes:
  postgres_data:
