"""enquiry-contact-form

Revision ID: 47ee312a34e6
Revises: 7c8a04480782
Create Date: 2025-10-12 15:22:24.529434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ee312a34e6'
down_revision: Union[str, Sequence[str], None] = '7c8a04480782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_contact_forms_id'), table_name='tbl_contact_forms')
    op.drop_table('tbl_contact_forms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_contact_forms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_contact_forms_pkey'))
    )
    op.create_index(op.f('ix_tbl_contact_forms_id'), 'tbl_contact_forms', ['id'], unique=False)
    # ### end Alembic commands ###
