name: FastAPI CI with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment file
        run: cp .env.dev .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: docker compose up -d --build

      - name: Wait for Postgres
        run: |
          timeout=60
          elapsed=0
          until docker exec fastapi_cms_db pg_isready; do
            echo "Waiting for Postgres..."
            sleep 2
            elapsed=$((elapsed + 2))
            if [ $elapsed -ge $timeout ]; then
              echo "Postgres did not start in time."
              exit 1
            fi
          done

      - name: Run tests
        run: docker exec fastapi_cms_app pytest --maxfail=1 --disable-warnings -q

      - name: Tear down
        if: always()
        run: docker compose down
